export const CHANGE_SEARCH = 'CHANGE_SEARCH';
export const SUBMIT_SEARCH = 'SUBMIT_SEARCH';
export const SUBMIT_SEARCH_SUCCESS = 'SUBMIT_SEARCH_SUCCESS';
export const SUBMIT_SEARCH_ERROR = 'SUBMIT_SEARCH_ERROR';